### ISSUE TITLE
Backup jobs

### ISSUE THREAD

**Issue by robstolarz** [SquaredLabs/nucore-uconn#44]
A list of backup solutions should be made and one should be implemented into the Helm chart.

**Comment by joshea0** [comment]
Came across [ark](https://github.com/heptio/ark) today which looks really promising. Although I think it may be meant for disaster recovery of the entire cluster and not just for app level backups. Regardless I wanted to make a note here since it is something we could really use. When we get a dedicated places for server/ops/k8s stuff I'll move this there.
